// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package consumer

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/twmb/franz-go/pkg/kgo"
	"github.com/twmb/franz-go/pkg/kmsg"
)

// NewMockKafkaConsumer creates a new instance of MockKafkaConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKafkaConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKafkaConsumer {
	mock := &MockKafkaConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKafkaConsumer is an autogenerated mock type for the KafkaConsumer type
type MockKafkaConsumer struct {
	mock.Mock
}

type MockKafkaConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKafkaConsumer) EXPECT() *MockKafkaConsumer_Expecter {
	return &MockKafkaConsumer_Expecter{mock: &_m.Mock}
}

// CommitOffsets provides a mock function for the type MockKafkaConsumer
func (_mock *MockKafkaConsumer) CommitOffsets(ctx context.Context, uncommitted map[string]map[int32]kgo.EpochOffset, onDone func(*kgo.Client, *kmsg.OffsetCommitRequest, *kmsg.OffsetCommitResponse, error)) {
	_mock.Called(ctx, uncommitted, onDone)
	return
}

// MockKafkaConsumer_CommitOffsets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitOffsets'
type MockKafkaConsumer_CommitOffsets_Call struct {
	*mock.Call
}

// CommitOffsets is a helper method to define mock.On call
//   - ctx context.Context
//   - uncommitted map[string]map[int32]kgo.EpochOffset
//   - onDone func(*kgo.Client, *kmsg.OffsetCommitRequest, *kmsg.OffsetCommitResponse, error)
func (_e *MockKafkaConsumer_Expecter) CommitOffsets(ctx interface{}, uncommitted interface{}, onDone interface{}) *MockKafkaConsumer_CommitOffsets_Call {
	return &MockKafkaConsumer_CommitOffsets_Call{Call: _e.mock.On("CommitOffsets", ctx, uncommitted, onDone)}
}

func (_c *MockKafkaConsumer_CommitOffsets_Call) Run(run func(ctx context.Context, uncommitted map[string]map[int32]kgo.EpochOffset, onDone func(*kgo.Client, *kmsg.OffsetCommitRequest, *kmsg.OffsetCommitResponse, error))) *MockKafkaConsumer_CommitOffsets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]map[int32]kgo.EpochOffset
		if args[1] != nil {
			arg1 = args[1].(map[string]map[int32]kgo.EpochOffset)
		}
		var arg2 func(*kgo.Client, *kmsg.OffsetCommitRequest, *kmsg.OffsetCommitResponse, error)
		if args[2] != nil {
			arg2 = args[2].(func(*kgo.Client, *kmsg.OffsetCommitRequest, *kmsg.OffsetCommitResponse, error))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKafkaConsumer_CommitOffsets_Call) Return() *MockKafkaConsumer_CommitOffsets_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockKafkaConsumer_CommitOffsets_Call) RunAndReturn(run func(ctx context.Context, uncommitted map[string]map[int32]kgo.EpochOffset, onDone func(*kgo.Client, *kmsg.OffsetCommitRequest, *kmsg.OffsetCommitResponse, error))) *MockKafkaConsumer_CommitOffsets_Call {
	_c.Run(run)
	return _c
}

// PollFetches provides a mock function for the type MockKafkaConsumer
func (_mock *MockKafkaConsumer) PollFetches(ctx context.Context) kgo.Fetches {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PollFetches")
	}

	var r0 kgo.Fetches
	if returnFunc, ok := ret.Get(0).(func(context.Context) kgo.Fetches); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kgo.Fetches)
		}
	}
	return r0
}

// MockKafkaConsumer_PollFetches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PollFetches'
type MockKafkaConsumer_PollFetches_Call struct {
	*mock.Call
}

// PollFetches is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockKafkaConsumer_Expecter) PollFetches(ctx interface{}) *MockKafkaConsumer_PollFetches_Call {
	return &MockKafkaConsumer_PollFetches_Call{Call: _e.mock.On("PollFetches", ctx)}
}

func (_c *MockKafkaConsumer_PollFetches_Call) Run(run func(ctx context.Context)) *MockKafkaConsumer_PollFetches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKafkaConsumer_PollFetches_Call) Return(fetches kgo.Fetches) *MockKafkaConsumer_PollFetches_Call {
	_c.Call.Return(fetches)
	return _c
}

func (_c *MockKafkaConsumer_PollFetches_Call) RunAndReturn(run func(ctx context.Context) kgo.Fetches) *MockKafkaConsumer_PollFetches_Call {
	_c.Call.Return(run)
	return _c
}
